name: pdsimage
dependencies:
- backports_abc=0.4=py27_0
- basemap=1.0.7=np110py27_0
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- freetype=2.5.5=0
- geos=3.3.3=0
- ipykernel=4.2.2=py27_0
- ipython=4.0.2=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.1=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.1.0=py27_0
- numpy=1.10.2=py27_0
- openssl=1.0.2e=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip
- ptyprocess=0.5=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pytz=2015.7=py27_0
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- requests=2.9.1=py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.16.1
- seaborn=0.6.0=np110py27_0
- setuptools=19.4=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - alabaster==0.7.7
  - babel==2.2.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - circles==0.1
  - cython==0.23.4
  - descartes==1.0.1
  - docutils==0.12
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - palettable==2.1.1
  - pdsimage==1.1.2
  - planetaryimage==0.3.0
  - pockets==0.3
  - pvl==0.2.0
  - shapely==1.5.13
  - snowballstemmer==1.2.1
  - sphinx==1.3.4
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-napoleon==0.4.3

